#! /bin/bash

DOCKER_NAME="image_name" # name image username in container
CONTAINER_NAME=$USER"-project_name" # name of container
SRC="YOUR/REPO/PATH" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=$(id -u) 
DOCKER_GROUP_ID=$(id -g)